# Generated by Django 4.1.3 on 2022-12-22 09:38

from django.db import migrations, models
import sns_test.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[sns_test.models.name_validator])),
                ('message', models.TextField(max_length=400)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
