# Generated by Django 4.1.3 on 2022-12-20 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('use_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemoninfo',
            old_name='pokemon_name',
            new_name='pokemons_name',
        ),
    ]
